### ISSUE TITLE
count_na - want to pass vars to count

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/hotfun#7]
Currently, can't pass any variables (just the data frame),  want to be able to pass data frame and a subset of vars to perform `count_na()` on

Also, print the legend with glue, not print so there are no quotes

**Comment by ddsjoberg** [comment]
@emilyvertosick this is done, right?

**Comment by emilyvertosick** [comment]
I think so - I'm not able to pass a list of variables, but I can pass a tibble with a select statement.

For example, this does not work:
trial %>% count_na(age, marker)

But this does work:
count_na(trial %>% select(age, marker))

If this is the intended behavior (which I think is fine) then I think this is done

**Comment by ddsjoberg** [comment]
We added `include = ` and `exclude = ` arguments.  Is that what they were meant for?

**Comment by ddsjoberg** [comment]
perhaps done?
